# Generated by Django 6.0.1 on 2026-03-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_remove_booking_status_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
